defmodule Problem2 do

  @doc "
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  iex |> Problem2.fib(0,1,0)
  "

  def even_add(v,c) when rem(v, 2) == 0 do
    v + c
  end

  def even_add(_v,c), do: c

  def fib(v,n,c) when v < 4000000 do
    fib(n, n+v, even_add(v,c))
  end

  def fib(_v,_n,c), do: c

end

IO.puts Problem2.fib(0,1,0)
